name: talaba_uz
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  email_otp: ^3.0.2
  hive: ^2.2.3
  get: ^4.6.6
  path_provider: ^2.1.2
  dio: ^5.5.0+1
  http: ^1.2.1
  fluttertoast: ^8.2.4
  flutter_carousel_widget: ^2.2.0
  introduction_screen: ^3.1.12
  percent_indicator: ^4.2.3
  custom_navigation_bar: ^0.8.2
  flutter_timer_countdown: ^1.0.7
  page_transition: ^2.1.0
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  carousel_indicator: ^1.0.6
  shared_preferences: ^2.2.3
  animated_bottom_navigation_bar: ^1.3.3
  stylish_bottom_bar: ^1.1.0
  connectivity_plus: ^6.0.2
  buttons_tabbar: ^1.3.8
  tab_container: ^3.5.2
  flutter_countdown_timer: ^4.1.0
  flutter_launcher_icons: ^0.13.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  google_sign_in: ^6.2.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "mock_me"
  ios: true
  image_path: "assets/icons/mock-me.png"
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
  - assets/icons/
  - assets/images/
  - assets/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
    - family: Inter-SemiBold
      fonts:
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
    - family: Inter-Medium
      fonts:
        - asset: assets/fonts/Inter/Inter-Medium.ttf
    - family: Inter-Bold
      fonts:
        - asset: assets/fonts/Inter/Inter-Bold.ttf
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf